---
title: "intro to spatial data"
format: html
execute:
  warning: false
  message: false
---


## downloading data

```{r}
library(readr)
library(sf)
library(ggplot2)
library(leaflet)
library(scales)
library(ggspatial)
library(dplyr)
library(here)

knb_url <- "https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn%3Auuid%3Aaceaecb2-1ce0-4d41-a839-d3607d32bb58"

download.file(url = knb_url, destfile = '../shapefile_demo_data.zip')

unzip('../shapefile_demo_data.zip', exdir = '../data')

file.remove('../shapefile_demo_data.zip')
```
```{r}
# read in shapefile using read_sf()
ak_regions <- read_sf(here("data/ak_regions_simp.shp"))

ak_regions_3338 <- ak_regions %>%
    st_transform(crs = 3338)
st_crs(ak_regions_3338)

plot(ak_regions_3338)
```



```{r}
unique(ak_regions_3338$region)
ak_regions_3338 %>%
    filter(region == "Southeast")

 # read in population data
pop <- read_csv("data/alaska_population.csv")

pop_4326 <- st_as_sf(pop,
                     coords = c('lng', 'lat'),
                     crs = 4326,
                     remove = F)

head(pop_4326)

pop_3338 <- st_transform(pop_4326, 
                         crs = 3338)

pop_joined <- st_join(pop_3338, 
                      ak_regions_3338, 
                      join = st_within)

head(pop_joined)

```






```{r}

pop_region <- pop_joined %>%
    as.data.frame() %>%
    group_by(region) %>%
    summarise(total_pop = sum(population))


pop_region_3338 <- left_join(ak_regions_3338, 
                             pop_region, 
                             by = "region")

# plot to check
plot(pop_region_3338["total_pop"])
```
```{r}
pop_mgmt_3338 <- pop_region_3338 %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop))

plot(pop_mgmt_3338["total_pop"])
```






